version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/tradecapture"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    # Only create PRs for minor/patch updates by default
    allow:
      - dependency-type: "direct"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

# Optionally enable automerging for minor/patch updates (requires repository setup)
# automerge:
#   when: 'security' # or 'all'