version: '3.8'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: trade
      POSTGRES_PASSWORD: tradepass
      POSTGRES_DB: trade_store
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD-SHELL", "mongo --eval \"db.adminCommand('ping')\" --quiet"]
      interval: 10s
      timeout: 5s
      retries: 5

# Optional: add Kafka/Zookeeper if you want to exercise streaming ingestion
# kafka:
#   image: bitnami/kafka:3
#   environment:
#     KAFKA_BROKER_ID: 1
#     KAFKA_LISTENERS: PLAINTEXT://:9092
#     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#   ports:
#     - "9092:9092"
#   depends_on:
#     - zookeeper
#
# zookeeper:
#   image: bitnami/zookeeper:3
#   environment:
#     ALLOW_ANONYMOUS_LOGIN: 'yes'
#   ports:
#     - "2181:2181"
