server:
  port: 8091

spring:
  application:
    name: trade-expiry
  datasource:
    url: ${EXPIRY_DB_URL:jdbc:postgresql://localhost:5432/trades}
    username: ${EXPIRY_DB_USER:postgres}
    password: ${EXPIRY_DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.jdbc.time_zone: UTC
  data:
    mongodb:
      uri: ${EXPIRY_MONGO_URI:mongodb://localhost:27017/trade_history}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

trade:
  expiry:
    fixedDelay: 60000
